### PR TITLE
Updated some of the graphics

### PR DESCRIPTION
**Pull request by deanhu2**
Hi, i really like your project and im interested in helping with it. 

Iv updated some of the graphics for now for my own test version however you are free to use them if you like in your own build and if its ok id like to help you continue to develop this project.

### CODE REVIEW

**Review by stepulak — APPROVED** [review]
These coin textures looks promising, I think I will use them... If you like to be listed in game's credits, let me know and I will add you right here.

**Review by stepulak — COMMENTED** [review]
These flowers look very good. I've already written you about coin textures, so if you like to be listed in game's credits, let me know and I will add you right here...

**Comment by deanhu2** [comment]
Sure being credited would be nice, I will continue to update some of the graphics for my own purposes and pull them so you are free to pick and choose which is best for the main branch. Is there anything you particularly want to be working on graphics/script wise i could help with?

**Review by stepulak — COMMENTED** [review]
I am currently working on a full snow and day "biome", so that I could create some basic maps for the game and for the campaign. Maybe the parallax backgrounds in snow theme would be nice to see. The textures located in folder assets/ are moved into assets/textures/. I've already managed to draw some other images for the game, so I would recommend you to update your branch.

**Pull request merged**
